### ISSUE TITLE
Spinner is broken because of space between div tags

### ISSUE THREAD

**Issue by gilmarsquinelato** [PolymerElements/paper-spinner#20]
Hello everyone!
I'm testing paper-spinner on my application in ruby on rails, and it broke if a space is putted between a specific closing and opening div.

this is the original
```html
<div class="spinner-layer layer-1">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
```

the div is .gap-patch

```html
<div class="spinner-layer layer-1">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div> <div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
```
even if I put the original code to be referenced in my application the ruby on rails break the lines in the node http-server that does not occur

**Comment by gilmarsquinelato** [comment]
I found the solution!
Just add float: left to .spinner-layer > div

**Comment by keanulee** [comment]
Adding a space between the <div>'s will cause a gap because they are `display: inline-block` (for more details see http://stackoverflow.com/questions/19038799/why-is-there-an-unexplainable-gap-between-these-inline-block-div-elements). The simplest way is to remove the gap. Is there any reason why you need the whitespace there?
