### ISSUE TITLE
paper-spinner weirdness on Edge browser

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-spinner#30]
`paper-spinner` isn't working properly on Edge, as you can see in the demo page:

![paper-spinner](https://cloud.githubusercontent.com/assets/12832388/10372238/2aae3df8-6de7-11e5-95b8-434a384ddac2.gif)

**Comment by bicknellr** [comment]
I've been trying this out and it always seems to be a problem with the last spinner in a group of adjacent spinners. Strangely, when more spinners are added directly after the last one the issue seems to transfer to the new, last spinner of the group. I've also tried iterating through all descendants of a series of spinners (where, again, only the last one was having this problem) and checking their classes, and nothing seems to be different as long as the `active` property of each is the same.

Adding `position: relative;` to the `#spinnerContainer` rule seems to stop the individual spinner layers from flying out of the outer container. However, this shouldn't have any notable effect given that `:host` has `position: relative;` and `.spinner-layer` has `position: absolute;`.

Right now, my guess is that these are both a result of some css animation bug, but I also don't have a reduced test case yet.

**Comment by kungufli** [comment]
@bicknellr thanks for looking on that, the problem is present also with only one spinner, not only on group of spinners (when you have a single spinner it's also the last one of the group, so the bug's behavior is consistent).

**Comment by kungufli** [comment]
Seems fixed in the last version of the element.
